name: "rust-starter"
description: "rust-starter is a template repository for Rust projects."
inputs:
  version:
    description: "rust-starter version to use, semver format without v prefix"
    required: false
    default: "0.1.13"
runs:
  using: "composite"
  steps:
    - name: Convert target
      id: convert
      shell: sh
      env:
        os: ${{ runner.os }} # Possible values are Linux, Windows, or macOS.
        arch: ${{ runner.arch }} # Possible values are X86, X64, ARM, or ARM64.
      run: |
        target="$os-$arch"
        case "$target" in
          macOS-ARM64) echo "target=aarch64-apple-darwin" >> "$GITHUB_OUTPUT" ;;
          Linux-X64) echo "target=x86_64-unknown-linux-gnu" >> "$GITHUB_OUTPUT" ;;
          Linux-ARM64) echo "target=aarch64-unknown-linux-gnu" >> "$GITHUB_OUTPUT" ;;
          *) echo "Unsupported os-arch target: $target" >&2; exit 1 ;;
        esac
    - name: Cache
      id: cache
      uses: actions/cache@v4
      with:
        path: /usr/local/bin/rust-starter
        key: rust-starter_v${{ inputs.version }}_${{ steps.convert.outputs.target }}
    - if: steps.cache.outputs.cache-hit != 'true'
      name: Install
      working-directory: ${{ runner.temp }}
      shell: sh
      env:
        GH_TOKEN: ${{ github.token }}
        version: ${{ inputs.version }}
        target: ${{ steps.convert.outputs.target }}
      run: |
        gh release download "v$version" --repo anttiharju/rust-starter --pattern "rust-starter-$target.tar.gz"
        tar -xzf "rust-starter-$target.tar.gz" rust-starter
        mv rust-starter /usr/local/bin
    - name: Run
      shell: sh
      env:
        wildcard: ${{ inputs.github-workflows-wildcard }}
        changes: ${{ inputs.changes }}
      run: |
        rust-starter
outputs:
  changed:
    description: "Boolean indicating if any changed files match paths in the wildcard file"
    value: ${{ steps.wildcard.outputs.changed }}
