name: "Commit release"
description: "Creates a release commit"
inputs:
  version:
    description: "Release version"
    required: true
  ANTTIHARJU_BOT_ID:
    description: "GitHub App ID for committing the release"
    required: true
  ANTTIHARJU_BOT_PRIVATE_KEY:
    description: "GitHub App private key for committing the release"
    required: true

runs:
  using: "composite"
  steps:
    - name: Generate commit token
      uses: actions/create-github-app-token@v1
      id: generate
      with:
        app-id: ${{ inputs.ANTTIHARJU_BOT_ID }}
        private-key: ${{ inputs.ANTTIHARJU_BOT_PRIVATE_KEY }}
        repositories: ${{ github.event.repository.name }}
    - name: Checkout
      uses: actions/checkout@v6
      with:
        token: ${{ steps.generate.outputs.token }}
        path: release
    - name: Create release commit
      working-directory: release
      shell: sh
      env:
        version: ${{ inputs.version }}
      run: |
        git reset --hard && git clean -df
        toml set Cargo.toml package.version "$version" > Cargo.toml.tmp && mv Cargo.toml.tmp Cargo.toml
        toml set Cargo.lock "package[0].version" "$version" > Cargo.lock.tmp && mv Cargo.lock.tmp Cargo.lock
        yq -i ".inputs.version.default = \"$version\"" action.yml
    - name: Commit changes
      uses: anttiharju/actions/commit-changes@v0
      with:
        author: "${{ github.actor }}[bot]"
        committer: "${{ github.actor }}[bot]"
        message: ${{ inputs.version }}
        working-directory: release
