name: "Detect changes"
description: "Decide what steps need running based on changes"
inputs:
  changes:
    description: "JSON array of changed files"
    required: true
runs:
  using: "composite"
  steps:
    - id: actionlint
      uses: anttiharju/compare-changes@v0
      with:
        github-workflows-wildcard: actionlint.yml
        changes: ${{ inputs.changes }}
    - id: rust
      uses: anttiharju/compare-changes@v0
      with:
        github-workflows-wildcard: rust.yml
        changes: ${{ inputs.changes }}
    - id: rs
      uses: anttiharju/compare-changes@v0
      with:
        github-workflows-wildcard: rs.yml
        changes: ${{ inputs.changes }}
    - id: brew
      uses: anttiharju/compare-changes@v0
      with:
        github-workflows-wildcard: brew.yml
        changes: ${{ inputs.changes }}
    - id: github
      uses: anttiharju/compare-changes@v0
      with:
        github-workflows-wildcard: github.yml
        changes: ${{ inputs.changes }}
    - id: nix
      uses: anttiharju/compare-changes@v0
      with:
        github-workflows-wildcard: nix.yml
        changes: ${{ inputs.changes }}
    - id: mkdocs
      uses: anttiharju/compare-changes@v0
      with:
        github-workflows-wildcard: mkdocs.yml
        changes: ${{ inputs.changes }}
    - id: prettier
      uses: anttiharju/compare-changes@v0
      with:
        github-workflows-wildcard: prettier.yml
        changes: ${{ inputs.changes }}
    - id: shellcheck
      uses: anttiharju/compare-changes@v0
      with:
        github-workflows-wildcard: shellcheck.yml
        changes: ${{ inputs.changes }}
    - id: src
      uses: anttiharju/compare-changes@v0
      with:
        github-workflows-wildcard: src.yml
        changes: ${{ inputs.changes }}
    - id: action
      uses: anttiharju/compare-changes@v0
      with:
        github-workflows-wildcard: action.yml
        changes: ${{ inputs.changes }}
outputs:
  actionlint:
    description: "Whether actionlint has changed"
    value: ${{ steps.actionlint.outputs.changed }}
  rust:
    description: "Whether Rust has changed"
    value: ${{ steps.rust.outputs.changed }}
  rs:
    description: "Whether *.rs has changed"
    value: ${{ steps.rs.outputs.changed }}
  brew:
    description: "Whether Brew has changed"
    value: ${{ steps.brew.outputs.changed }}
  github:
    description: "Whether GitHub has changed"
    value: ${{ steps.github.outputs.changed }}
  nix:
    description: "Whether Nix has changed"
    value: ${{ steps.nix.outputs.changed }}
  release:
    description: "Whether any release has changed"
    value: ${{ steps.brew.outputs.changed || steps.github.outputs.changed || steps.nix.outputs.changed }}
  mkdocs:
    description: "Whether MkDocs has changed"
    value: ${{ steps.mkdocs.outputs.changed }}
  prettier:
    description: "Whether Prettier has changed"
    value: ${{ steps.prettier.outputs.changed }}
  shellcheck:
    description: "Whether ShellCheck has changed"
    value: ${{ steps.shellcheck.outputs.changed }}
  src:
    description: "Whether src has changed"
    value: ${{ steps.src.outputs.changed }}
  action:
    description: "Whether action has changed"
    value: ${{ steps.action.outputs.changed }}
