# cargo build --all-features --target aarch64-apple-darwin
[target.aarch64-apple-darwin]
linker = "scripts/zcc/aarch64-apple-darwin.sh"

# cargo build --all-features --target aarch64-unknown-linux-gnu
[target.aarch64-unknown-linux-gnu]
linker = "scripts/zcc/aarch64-unknown-linux-gnu.sh"

# cargo build --all-features --target x86_64-unknown-linux-gnu
[target.x86_64-unknown-linux-gnu]
linker = "scripts/zcc/x86_64-unknown-linux-gnu.sh"
